name: Create Release

on:
    push:
        tags:
            - 'v*'
    pull_request:
        branches:
            - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # This ensures all commits and tags are fetched

      - name: Create Release
        run: |
          TAG_NAME=${{  github.ref_name }}
          gh release create $TAG_NAME -t $TAG_NAME -n 'Release $TAG_NAME' --target main
